# Generated by Django 3.2 on 2022-02-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='password',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.CharField(default=0, max_length=32),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='passwords',
            field=models.CharField(default=0, max_length=32),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='username',
            field=models.CharField(default=0, max_length=32),
        ),
    ]
