# Generated by Django 3.2 on 2022-02-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220222_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.CharField(default=0, max_length=128),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='passwords',
            field=models.CharField(default=0, max_length=128),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(default=0, max_length=128),
        ),
    ]
